services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - ${POSTGRES_PORT}:5432
    entrypoint: ["/docker-entrypoint-initdb.d/init-db.sh"]

volumes:
  pgdata: