version: '3.9'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db/pgdata:/var/lib/postgresql
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - ${POSTGRES_PORT}:5432
    expose:
      - 5432
volumes:
  pgdata: